package com.example.hubert.hubquiz;


import java.util.List;

public class QandA {
    private String pyt [] = {
            "Afganistan",
            "Albania",
            "Algieria",
            "Andora",
            "Angola",
            "Antigua i Barbuda",
            "Arabia Saudyjska",
            "Argentyna",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbejdżan",
            "Bahamy",
            "Bahrajn",
            "Bangladesz",
            "Barbados",
            "Belgia",
            "Belize",
            "Benin",
            "Bhutan",
            "Białoruś",
            "Boliwia",
            "Bośnia i Hercegowina",
            "Botswana",
            "Brazylia",
            "Brunei",
            "Bułgaria",
            "Burkina Faso",
            "Burundi",
            "Chile",
            "Chiny",
            "Chorwacja",
            "Cypr",
            "Czad",
            "Czarnogóra",
            "Czechy",
            "Dania",
            "Demokratyczna Republika Konga",
            "Dominika",
            "Dominikana",
            "Dżibuti",
            "Egipt",
            "Ekwador",
            "Erytrea",
            "Estonia",
            "Etiopia",
            "Filipiny",
            "Finlandia",
            "Fidżi",
            "Francja",
            "Gabon",
            "Gambia",
            "Ghana",
            "Gqinea Równikowa",
            "Grecja",
            "Grenada",
            "Gruzja",
            "Gujana",
            "Gwatemala",
            "Gwinea",
            "GwineaBissau",
            "Haiti",
            "Hiszpania",
            "Holandia",
            "Honduras",
            "Indie",
            "Indonezja",
            "Irak",
            "Iran",
            "Irlandia",
            "Islandia",
            "Izrael",
            "Jamajka",
            "Japonia",
            "Jemen",
            "Jordania",
            "Kambodża",
            "Kamerun",
            "Kanada",
            "Katar",
            "Kazachstan",
            "Kenia",
            "Kirgistan",
            "Kiribati",
            "Kolumbia",
            "Komory",
            "Kongo",
            "KoreaPołnocna",
            "KoreaPołudniowa",
            "Kostaryka",
            "Kuba",
            "Kuwejt",
            "Laos",
            "Lesotho",
            "Liban",
            "Liberia",
            "Libia",
            "Liechtenstein",
            "Litwa",
            "Luksemburg",
            "Łotwa",
            "Macedonia",
            "Madagaskar",
            "Malawi",
            "Malediwy",
            "Malezja",
            "Mali",
            "Malta",
            "Maroko",
            "Mauretania",
            "Mauritius",
            "Meksyk",
            "Mikronezja",
            "Mjanma",
            "Mołdawia",
            "Monako",
            "Mongolia",
            "Mozambik",
            "Namibia",
            "Nauru",
            "Nepal",
            "Niemcy",
            "Niger",
            "Nigeria",
            "Nikaragua",
            "Norwegia",
            "NowaZelandia",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua-Nowa Gwinea",
            "Paragwaj",
            "Peru",
            "Polska",
            "Południowa Afryka",
            "Portugalia",
            "Republika Środkowo Afrykańska",
            "Republika Zielonego Przylądka",
            "Rosja",
            "Rumunia",
            "Rwanda",
            "Saint Kittsi Nevis",
            "Saint Lucia",
            "Saint Vincenti Grenadyny",
            "Salwador",
            "Samoa",
            "San Marino",
            "Senegal",
            "Serbia",
            "Seszele",
            "Sierra Leone",
            "Singapur",
            "Słowacja",
            "Słowenia",
            "Somalia",
            "Sri Lanka",
            "Stany Zjednoczone",
            "Suazi",
            "Sudan",
            "Sudan Południowy",
            "Surinam",
            "Syria",
            "Szwajcaria",
            "Szwecja",
            "Tadżykistan",
            "Tajlandia",
            "Tanzania",
            "Timor Wschodni",
            "Togo",
            "Tonga",
            "Trynidadi Tobago",
            "Tunezja",
            "Turcja",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraina",
            "Urugwaj",
            "Uzbekistan",
            "Vanuatu",
            "Watykan",
            "Wenezuela",
            "Węgry",
            "Wielka Brytania",
            "Wietnam",
            "Włochy",
            "Wybrzeże Kości Słoniowej",
            "Wyspu Marshalla",
            "Wyspy Salomona",
            "Wyspy Świętego Tomaszai Książęca",
            "Zambia",
            "Zimbabwe",
            "Zjednoczone Emirady Arabskie"};

    private int img [] = {
            R.drawable.afganistan,
            R.drawable.albania,
            R.drawable.algieria,
            R.drawable.andora,
            R.drawable.angola,
            R.drawable.antig_i_barbuda,
            R.drawable.arabia_saudyjska,
            R.drawable.argentyna,
            R.drawable.armenia,
            R.drawable.australia,
            R.drawable.austria,
            R.drawable.azerbejdzan,
            R.drawable.bahamy,
            R.drawable.bahrajn,
            R.drawable.bangladesz,
            R.drawable.barbados,
            R.drawable.belgia,
            R.drawable.belize,
            R.drawable.benin,
            R.drawable.bhutan,
            R.drawable.bialorus,
            R.drawable.boliwia,
            R.drawable.bosnia_i_hercegowina,
            R.drawable.botswana,
            R.drawable.brazylia,
            R.drawable.brunei,
            R.drawable.bulgaria,
            R.drawable.burkin_faso,
            R.drawable.burundi,
            R.drawable.chile,
            R.drawable.chiny,
            R.drawable.chorwacja,
            R.drawable.cypr,
            R.drawable.czad,
            R.drawable.czarnogora,
            R.drawable.czechy,
            R.drawable.dania,
            R.drawable.demokratyczna_republika_konga,
            R.drawable.dominika,
            R.drawable.dominikana,
            R.drawable.dzibuti,
            R.drawable.egipt,
            R.drawable.ekwador,
            R.drawable.erytrea,
            R.drawable.estonia,
            R.drawable.etiopia,
            R.drawable.filipiny,
            R.drawable.finlandia,
            R.drawable.fidzi,
            R.drawable.francja,
            R.drawable.gabon,
            R.drawable.gambia,
            R.drawable.ghana,
            R.drawable.gwinearownikowa,
            R.drawable.grecja,
            R.drawable.grenada,
            R.drawable.gruzja,
            R.drawable.gujana,
            R.drawable.gwatemala,
            R.drawable.gwinea,
            R.drawable.gwineabissau,
            R.drawable.haiti,
            R.drawable.hiszpania,
            R.drawable.holandia,
            R.drawable.honduras,
            R.drawable.indie,
            R.drawable.indonezja,
            R.drawable.irak,
            R.drawable.iran,
            R.drawable.irlandia,
            R.drawable.islandia,
            R.drawable.izrael,
            R.drawable.jamajka,
            R.drawable.japonia,
            R.drawable.jemen,
            R.drawable.jordania,
            R.drawable.kambodza,
            R.drawable.kamerun,
            R.drawable.kanada,
            R.drawable.katar,
            R.drawable.kazachstan,
            R.drawable.kenia,
            R.drawable.kirgistan,
            R.drawable.kiribati,
            R.drawable.kolumbia,
            R.drawable.komory,
            R.drawable.kongo,
            R.drawable.korea_polnocna,
            R.drawable.korea_poludniowa,
            R.drawable.kostaryka,
            R.drawable.kuba,
            R.drawable.kuwejt,
            R.drawable.laos,
            R.drawable.lesotho,
            R.drawable.liban,
            R.drawable.liberia,
            R.drawable.libia,
            R.drawable.liechtenstein,
            R.drawable.litwa,
            R.drawable.luksemburg,
            R.drawable.lotwa,
            R.drawable.macedonia,
            R.drawable.madagaskar,
            R.drawable.malawi,
            R.drawable.malediwy,
            R.drawable.malezja,
            R.drawable.mali,
            R.drawable.malta,
            R.drawable.maroko,
            R.drawable.mauretania,
            R.drawable.mauritius,
            R.drawable.meksyk,
            R.drawable.mikronezja,
            R.drawable.mjanma,
            R.drawable.moldawia,
            R.drawable.monako,
            R.drawable.mongolia,
            R.drawable.mozambik,
            R.drawable.namibia,
            R.drawable.nauru,
            R.drawable.nepal,
            R.drawable.niemcy,
            R.drawable.niger,
            R.drawable.nigeria,
            R.drawable.nikaragua,
            R.drawable.norwegia,
            R.drawable.nowa_zelandia,
            R.drawable.oman,
            R.drawable.pakistan,
            R.drawable.palau,
            R.drawable.panama,
            R.drawable.papuowagwinea,
            R.drawable.paragwaj,
            R.drawable.peru,
            R.drawable.polska,
            R.drawable.poludniowa_afryka,
            R.drawable.portugal,
            R.drawable.republik_srodkowoafrykanska,
            R.drawable.republika_zielonego_przyladk,
            R.drawable.rosja,
            R.drawable.rumunia,
            R.drawable.rwanda,
            R.drawable.saint_kitts_i_nevis,
            R.drawable.saint_lucia,
            R.drawable.saint_vincent_i_grenadyny,
            R.drawable.salwador,
            R.drawable.samoa,
            R.drawable.san_marino,
            R.drawable.senegal,
            R.drawable.serbia,
            R.drawable.seszele,
            R.drawable.sierra_leone,
            R.drawable.sigapur,
            R.drawable.slowacja,
            R.drawable.slowenia,
            R.drawable.somalia,
            R.drawable.sri_lanka,
            R.drawable.stany_zjednoczone,
            R.drawable.suazi,
            R.drawable.sudan,
            R.drawable.sudan_poludniowy,
            R.drawable.surinam,
            R.drawable.syria,
            R.drawable.szwajcaria,
            R.drawable.szwecja,
            R.drawable.tadzykistan,
            R.drawable.tajlandia,
            R.drawable.tanzania,
            R.drawable.timor_wschodni,
            R.drawable.togo,
            R.drawable.tonga,
            R.drawable.trinidad_i_tobago,
            R.drawable.tunezja,
            R.drawable.turcja,
            R.drawable.turkmenistan,
            R.drawable.tuvalu,
            R.drawable.uganda,
            R.drawable.ukraina,
            R.drawable.urugwaj,
            R.drawable.uzbekistan,
            R.drawable.vanuatu,
            R.drawable.watykan,
            R.drawable.wenezuela,
            R.drawable.wegry,
            R.drawable.wielka_brytania,
            R.drawable.wietnam,
            R.drawable.wlochy,
            R.drawable.wybrzeze_kosci_sloniowej,
            R.drawable.wyspy_marshalla,
            R.drawable.wyspy_salomona,
            R.drawable.wyspy_swietego_tomasza_i_ksiazeca,
            R.drawable.zambia,
            R.drawable.zimbabwe,
            R.drawable.zjednoczone_emiraty_arabskie};

    public String getName(int a){
        String question=pyt[a];
        return question;
    }
    public  int getLength(){
        return pyt.length;
    }
    public int getImg(int a){
        int ima = img[a];
        return ima;
    }

}
